"""cria tabelas do modulo compras

Revision ID: 9f46b60d39e1
Revises: 
Create Date: 2026-05-21 19:23:33.870290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f46b60d39e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('prazo_entrega', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fornecedores_cnpj'), 'fornecedores', ['cnpj'], unique=True)
    op.create_index(op.f('ix_fornecedores_id'), 'fornecedores', ['id'], unique=False)
    op.create_table('solicitacoes_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False, comment='Referência ao produto no módulo Estoque (externo)'),
    sa.Column('produto_nome', sa.String(length=255), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitacoes_compra_id'), 'solicitacoes_compra', ['id'], unique=False)
    op.create_table('cotacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitacao_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False, comment='pendente | aprovada | recusada'),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes_compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cotacoes_id'), 'cotacoes', ['id'], unique=False)
    op.create_table('ordens_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cotacao_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False, comment='aberta | parcial | encerrada | cancelada'),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('data_previsao', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cotacao_id'], ['cotacoes.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordens_compra_id'), 'ordens_compra', ['id'], unique=False)
    op.create_table('historico_status_oc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordem_compra_id', sa.Integer(), nullable=False),
    sa.Column('status_anterior', sa.String(length=10), nullable=True, comment='aberta | parcial | encerrada | cancelada'),
    sa.Column('status_novo', sa.String(length=10), nullable=False),
    sa.Column('alterado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ordem_compra_id'], ['ordens_compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_status_oc_id'), 'historico_status_oc', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historico_status_oc_id'), table_name='historico_status_oc')
    op.drop_table('historico_status_oc')
    op.drop_index(op.f('ix_ordens_compra_id'), table_name='ordens_compra')
    op.drop_table('ordens_compra')
    op.drop_index(op.f('ix_cotacoes_id'), table_name='cotacoes')
    op.drop_table('cotacoes')
    op.drop_index(op.f('ix_solicitacoes_compra_id'), table_name='solicitacoes_compra')
    op.drop_table('solicitacoes_compra')
    op.drop_index(op.f('ix_fornecedores_id'), table_name='fornecedores')
    op.drop_index(op.f('ix_fornecedores_cnpj'), table_name='fornecedores')
    op.drop_table('fornecedores')
    # ### end Alembic commands ###
